import jsPDF from "jspdf";
import budgetflowLogo from "../assets/budgetflow-logo.png";

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();

    img.onload = () => resolve(img);
    img.onerror = reject;

    img.src = src;
  });
}

async function loadFont(doc) {
  const response = await fetch("/fonts/NotoSans-Regular.ttf");

  if (!response.ok) {
    throw new Error("Font file not found.");
  }

  const buffer = await response.arrayBuffer();

  const uint8Array = new Uint8Array(buffer);

  let binary = "";

  for (let i = 0; i < uint8Array.length; i++) {
    binary += String.fromCharCode(uint8Array[i]);
  }

  const base64 = btoa(binary);

  doc.addFileToVFS("NotoSans-Regular.ttf", base64);
  doc.addFont("NotoSans-Regular.ttf", "NotoSans", "normal");

  doc.setFont("NotoSans", "normal");
}

async function tryLoadBranding(doc) {
  try {
    await loadFont(doc);
  } catch (error) {
    console.warn("Falling back to default PDF font:", error);
    doc.setFont("helvetica", "normal");
  }

  let logo = null;

  try {
    logo = await loadImage(budgetflowLogo);
  } catch (error) {
    console.warn("Logo unavailable, continuing without logo:", error);
  }

  return {
    logo,
  };
}

export async function exportCompoundInterestPDF({
  currency,
  principal,
  monthlyContribution,
  interestRate,
  inflationRate,
  years,
  frequency,
  futureValue,
  totalContributions,
  interestEarned,
  inflationAdjustedValue,
  rateComparisonData,
  yearlyData,
}) {
  const doc = new jsPDF();
  const { logo } = await tryLoadBranding(doc);

  // --------------------------------------------------
  // HEADER
  // --------------------------------------------------

  if (logo) {
    doc.addImage(logo, "PNG", 20, 12, 35, 35);
  }

  if (doc.getFontList()?.NotoSans) {
    doc.setFont("NotoSans", "normal");
  } else {
    doc.setFont("helvetica", "normal");
  }
  doc.setFontSize(20);
  doc.text("Compound Interest", logo ? 65 : 20, 25);

  doc.setFontSize(12);
  doc.text("Calculation Report", logo ? 65 : 20, 33);

  doc.setFontSize(9);
  doc.text("Generated by BudgetFlow", logo ? 65 : 20, 40);

  let y = 58;

  // --------------------------------------------------
  // MONEY FORMATTER
  // --------------------------------------------------

  const formatMoney = (value) =>
    `${currency}${Number(value).toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;

  // --------------------------------------------------
  // INVESTMENT DETAILS
  // --------------------------------------------------

  doc.setFontSize(14);
  doc.text("Investment Details", 20, y);

  y += 10;

  doc.setFontSize(10);

  const details = [
    ["Initial Investment", formatMoney(principal)],
    ["Monthly Contribution", formatMoney(monthlyContribution)],
    ["Interest Rate", `${interestRate}%`],
    ["Inflation Rate", `${inflationRate}%`],
    ["Investment Duration", `${years} years`],
    ["Compounding Frequency", frequency],
  ];

  details.forEach(([label, value]) => {
    doc.text(`${label}:`, 20, y);
    doc.text(value, 100, y);

    y += 7;
  });

  // --------------------------------------------------
  // INVESTMENT SUMMARY
  // --------------------------------------------------

  y += 8;

  doc.setFontSize(14);
  doc.text("Investment Summary", 20, y);

  y += 10;

  doc.setFontSize(10);

  const summary = [
    ["Future Value", formatMoney(futureValue)],
    ["Total Contributions", formatMoney(totalContributions)],
    ["Interest Earned", formatMoney(interestEarned)],
    ["Inflation Adjusted Value", formatMoney(inflationAdjustedValue)],
  ];

  summary.forEach(([label, value]) => {
    doc.text(`${label}:`, 20, y);
    doc.text(value, 100, y);

    y += 7;
  });

  // --------------------------------------------------
  // RATE COMPARISON
  // --------------------------------------------------

  if (rateComparisonData?.length > 0) {
    y += 8;

    doc.setFontSize(14);
    doc.text("Interest Rate Comparison", 20, y);

    y += 10;

    doc.setFontSize(10);

    rateComparisonData.forEach((item) => {
      // Prevent content from running off the page
      if (y > 275) {
        doc.addPage();
        y = 20;
      }

      doc.text(`${item.rate}%`, 20, y);
      doc.text(formatMoney(item.futureValue), 100, y);

      y += 7;
    });
  }

  // --------------------------------------------------
  // YEARLY BREAKDOWN
  // --------------------------------------------------

  if (yearlyData?.length > 0) {
    y += 8;

    doc.setFontSize(14);
    doc.text("Yearly Breakdown", 20, y);

    y += 10;

    doc.setFontSize(10);

    yearlyData.forEach((item) => {
      if (y > 275) {
        doc.addPage();
        y = 20;

        if (doc.getFontList()?.NotoSans) {
          doc.setFont("NotoSans", "normal");
        } else {
          doc.setFont("helvetica", "normal");
        }
        doc.setFontSize(10);
      }

      doc.text(`Year ${item.year}`, 20, y);
      doc.text(formatMoney(item.value), 100, y);

      y += 7;
    });
  }

  // --------------------------------------------------
  // FOOTER
  // --------------------------------------------------

  doc.setFontSize(8);
  doc.setTextColor(100);

  doc.text("Generated by BudgetFlow Compound Interest Calculator", 20, 290);

  // Save PDF
  doc.save("BudgetFlow-Compound-Interest-Calculation.pdf");
}

export default exportCompoundInterestPDF;
