import jsPDF from "jspdf";
import budgetflowLogo from "../assets/budgetflow-logo.png";

const loadImage = (src) => new Promise((resolve, reject) => {
  const image = new Image();
  image.onload = () => resolve(image);
  image.onerror = reject;
  image.src = src;
});

async function loadFont(doc) {
  const response = await fetch("/fonts/NotoSans-Regular.ttf");
  if (!response.ok) throw new Error("Font file not found.");
  const bytes = new Uint8Array(await response.arrayBuffer());
  let binary = "";
  bytes.forEach((byte) => { binary += String.fromCharCode(byte); });
  doc.addFileToVFS("NotoSans-Regular.ttf", btoa(binary));
  doc.addFont("NotoSans-Regular.ttf", "NotoSans", "normal");
  doc.setFont("NotoSans", "normal");
}

export async function exportBudgetHistoryPDF({ entry, currencySymbol }) {
  const doc = new jsPDF();
  let logo;
  try { logo = await loadImage(budgetflowLogo); } catch { logo = null; }
  try { await loadFont(doc); } catch (error) { console.warn("Unable to load PDF currency font:", error); }
  const font = doc.getFontList()?.NotoSans ? "NotoSans" : "helvetica";
  const money = (value) => `${currencySymbol}${Number(value || 0).toLocaleString()}`;
  const newPage = () => { doc.addPage(); y = 22; };
  let y = 20;

  if (logo) doc.addImage(logo, "PNG", 20, 12, 30, 30);
  doc.setFont(font, "normal"); doc.setFontSize(20);
  doc.text("Budget History", logo ? 60 : 20, 25);
  doc.setFont(font, "normal"); doc.setFontSize(11);
  doc.text(`${entry.label} - Generated by BudgetFlow`, logo ? 60 : 20, 33);
  y = 55;

  doc.setFont(font, "normal"); doc.setFontSize(14); doc.text("Monthly Summary", 20, y); y += 10;
  doc.setFont(font, "normal"); doc.setFontSize(10);
  [["Income", entry.income], ["Total Budget", entry.budgetTotal], ["Expenses", entry.expenses], [entry.remaining < 0 ? "Over Budget" : "Remaining", Math.abs(entry.remaining)]].forEach(([label, value]) => { doc.text(label, 20, y); doc.text(money(value), 115, y, { align: "right" }); y += 7; });

  y += 8; doc.setFont(font, "normal"); doc.setFontSize(14); doc.text("Budget Allocation", 20, y); y += 9;
  doc.setFontSize(10); entry.budgets.forEach((budget) => { if (y > 276) newPage(); doc.setFont(font, "normal"); doc.text(budget.category, 20, y); doc.text(money(budget.amount), 115, y, { align: "right" }); y += 7; });
  if (!entry.budgets.length) { doc.setFont(font, "normal"); doc.text("No budget set.", 20, y); y += 7; }

  y += 8; if (y > 270) newPage(); doc.setFont(font, "normal"); doc.setFontSize(14); doc.text("Expenses by Category", 20, y); y += 9;
  const expenses = Object.entries(entry.expensesByCategory);
  doc.setFontSize(10); expenses.forEach(([category, total]) => { if (y > 276) newPage(); doc.setFont(font, "normal"); doc.text(category, 20, y); doc.text(money(total), 115, y, { align: "right" }); y += 6; (entry.expenseItemsByCategory[category] || []).forEach((item) => { if (y > 276) newPage(); doc.text(item.description || "Expense", 27, y); doc.text(`${item.date || ""}  ${money(item.amount)}`, 115, y, { align: "right" }); y += 6; }); y += 2; });
  if (!expenses.length) { doc.setFont(font, "normal"); doc.text("No expenses recorded.", 20, y); }

  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) { doc.setPage(page); doc.setFontSize(8); doc.setTextColor(100); doc.text(`BudgetFlow - ${entry.label} - Page ${page} of ${pages}`, 20, 290); doc.setTextColor(0); }
  doc.save(`BudgetFlow-Budget-History-${entry.month}.pdf`);
}

export default exportBudgetHistoryPDF;
