import { useState } from "react";
import { toast } from "react-hot-toast";
import YearlyBreakdownTable from "../components/YearlyBreakdownTable";
import CompoundInterestChart from "../components/CompoundInterestChart";
import { calculateCompoundInterest } from "../utils/compoundInterest";
import CompoundInterestSummary from "../components/CompoundInterestSummary";
import CompoundInterestForm from "../components/CompoundInterestForm";
import RateComparisonChart from "../components/RateComparisonChart";
import RateComparisonControls from "../components/RateComparisonControls";
import { exportCompoundInterestPDF } from "../utils/exportCompoundInterestPDF";

function CompoundInterest() {
  const [currency, setCurrency] = useState("₦");
  const [principal, setPrincipal] = useState(100000);
  const [monthlyContribution, setMonthlyContribution] = useState(25000);
  const [years, setYears] = useState(10);
  const [frequency, setFrequency] = useState("Monthly");
  const [growthView, setGrowthView] = useState("Yearly");

  const [interestRate, setInterestRate] = useState(12);

  const [inflationRate, setInflationRate] = useState(8);
  const [comparisonRates, setComparisonRates] = useState([10, 12, 15]);

  const ratesToCompare = [
    ...new Set([...comparisonRates, Number(interestRate)]),
  ].sort((a, b) => a - b);
  console.log("ratesToCompare:", ratesToCompare);

  const {
    futureValue,
    totalContributions,
    interestEarned,
    inflationAdjustedValue,
    yearlyData,
    monthlyData,
    rateComparisonData,
    rateComparisonGrowthData,
  } = calculateCompoundInterest({
    principal,
    monthlyContribution,
    interestRate,
    inflationRate,
    years,
    frequency,
    comparisonRates: ratesToCompare,
  });

  const handleExportPDF = async () => {
    await exportCompoundInterestPDF({
      currency,
      principal,
      monthlyContribution,
      interestRate,
      inflationRate,
      years,
      frequency,
      futureValue,
      totalContributions,
      interestEarned,
      inflationAdjustedValue,
      rateComparisonData,
      yearlyData,
    });
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopyResults = async () => {
    const results = `
BudgetFlow Compound Interest Calculation

Initial Investment: ${currency}${Number(principal).toLocaleString()}
Monthly Contribution: ${currency}${Number(monthlyContribution).toLocaleString()}
Interest Rate: ${interestRate}%
Inflation Rate: ${inflationRate}%
Investment Duration: ${years} years
Compounding Frequency: ${frequency}

Investment Summary

Future Value: ${currency}${Number(futureValue).toLocaleString(undefined, {
      maximumFractionDigits: 2,
    })}

Total Contributions: ${currency}${Number(totalContributions).toLocaleString(
      undefined,
      {
        maximumFractionDigits: 2,
      },
    )}

Interest Earned: ${currency}${Number(interestEarned).toLocaleString(undefined, {
      maximumFractionDigits: 2,
    })}

Inflation Adjusted Value: ${currency}${Number(
      inflationAdjustedValue,
    ).toLocaleString(undefined, {
      maximumFractionDigits: 2,
    })}

Generated by BudgetFlow
  `.trim();

    try {
      await navigator.clipboard.writeText(results);

      toast.success("Calculation copied to clipboard!");
    } catch (error) {
      toast.error("Unable to copy calculation.");
      console.error(error);
    }
  };

  return (
    <section className="space-y-6">
      <h1 className="text-3xl font-bold">Compound Interest Calculator</h1>

      <CompoundInterestForm
        principal={principal}
        setPrincipal={setPrincipal}
        monthlyContribution={monthlyContribution}
        setMonthlyContribution={setMonthlyContribution}
        interestRate={interestRate}
        setInterestRate={setInterestRate}
        inflationRate={inflationRate}
        setInflationRate={setInflationRate}
        years={years}
        setYears={setYears}
        frequency={frequency}
        setFrequency={setFrequency}
        currency={currency}
        setCurrency={setCurrency}
      />

      <CompoundInterestSummary
        currency={currency}
        futureValue={futureValue}
        totalContributions={totalContributions}
        interestEarned={interestEarned}
        inflationAdjustedValue={inflationAdjustedValue}
      />

      <div className="flex flex-wrap gap-3">
        <button
          type="button"
          onClick={handleExportPDF}
          className="rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white transition hover:bg-indigo-700"
        >
          📄 Export PDF
        </button>

        <button
          type="button"
          onClick={handlePrint}
          className="rounded-lg border border-slate-300 bg-white px-5 py-3 font-semibold text-slate-700 transition hover:bg-slate-50"
        >
          🖨️ Print
        </button>

        <button
          type="button"
          onClick={handleCopyResults}
          className="rounded-lg border border-slate-300 bg-white px-5 py-3 font-semibold text-slate-700 transition hover:bg-slate-50"
        >
          📋 Copy Results
        </button>
      </div>

      {growthView === "Yearly" ? (
        <>
          <CompoundInterestChart
            data={yearlyData}
            currency={currency}
            growthView={growthView}
            setGrowthView={setGrowthView}
            xKey="year"
          />

          <YearlyBreakdownTable data={yearlyData} currency={currency} />
        </>
      ) : (
        <>
          <CompoundInterestChart
            data={monthlyData}
            currency={currency}
            growthView={growthView}
            setGrowthView={setGrowthView}
            xKey="month"
          />

          <YearlyBreakdownTable data={monthlyData} currency={currency} />
        </>
      )}

      {/* Interest Rate Comparison */}

      <RateComparisonControls
        comparisonRates={comparisonRates}
        setComparisonRates={setComparisonRates}
        currentRate={Number(interestRate)}
      />

      <RateComparisonChart
        data={rateComparisonGrowthData}
        currency={currency}
        comparisonRates={ratesToCompare}
        currentRate={Number(interestRate)}
      />

      <div className="rounded-xl bg-white p-6 shadow-md">
        <h2 className="mb-2 text-xl font-semibold">Interest Rate Comparison</h2>

        <p className="mb-6 text-sm text-slate-500">
          See how different interest rates could affect your final investment
          value.
        </p>

        <div className="space-y-3">
          {rateComparisonData.map((item) => (
            <div
              key={item.rate}
              className="flex items-center justify-between rounded-lg bg-slate-50 p-4"
            >
              <span className="font-medium">{item.rate}%</span>

              <span className="font-bold text-slate-900">
                {currency}
                {item.futureValue.toLocaleString(undefined, {
                  maximumFractionDigits: 2,
                })}
              </span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default CompoundInterest;
