function FinancialInsights({
  currency,
  years,
  futureValue,
  totalContributions,
  interestEarned,
  inflationAdjustedValue,
  rateComparisonData,
}) {
  const safeFutureValue = Number(futureValue) || 0;
  const safeTotalContributions = Number(totalContributions) || 0;
  const safeInterestEarned = Number(interestEarned) || 0;
  const safeInflationAdjustedValue = Number(inflationAdjustedValue) || 0;

  const interestPercentage =
    safeFutureValue > 0
      ? (safeInterestEarned / safeFutureValue) * 100
      : 0;

  const inflationImpact =
    safeFutureValue > 0
      ? safeFutureValue - safeInflationAdjustedValue
      : 0;

  const inflationImpactPercentage =
    safeFutureValue > 0
      ? (inflationImpact / safeFutureValue) * 100
      : 0;

  const totalGrowth =
    safeTotalContributions > 0
      ? ((safeFutureValue - safeTotalContributions) /
          safeTotalContributions) *
        100
      : 0;

  const bestComparison =
    rateComparisonData?.length > 0
      ? [...rateComparisonData].sort(
          (a, b) => b.futureValue - a.futureValue,
        )[0]
      : null;

  const formatMoney = (value) =>
    `${currency}${Number(value).toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;

  return (
    <section className="rounded-xl bg-white p-6 shadow-md">
      <div className="mb-6">
        <h2 className="text-xl font-semibold">
          Financial Insights
        </h2>

        <p className="mt-1 text-sm text-slate-500">
          A quick overview of what your investment projection means.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {/* Investment Growth */}
        <div className="rounded-lg bg-indigo-50 p-5">
          <p className="text-sm font-medium text-indigo-700">
            Investment Growth
          </p>

          <p className="mt-2 text-2xl font-bold text-indigo-900">
            {totalGrowth.toFixed(2)}%
          </p>

          <p className="mt-2 text-sm text-indigo-700">
            Your projected investment grows by{" "}
            {totalGrowth.toFixed(2)}% above your total contributions.
          </p>
        </div>

        {/* Interest Contribution */}
        <div className="rounded-lg bg-green-50 p-5">
          <p className="text-sm font-medium text-green-700">
            Interest Contribution
          </p>

          <p className="mt-2 text-2xl font-bold text-green-900">
            {interestPercentage.toFixed(2)}%
          </p>

          <p className="mt-2 text-sm text-green-700">
            Approximately {interestPercentage.toFixed(2)}% of your
            final investment value comes from earned interest.
          </p>
        </div>

        {/* Contributions */}
        <div className="rounded-lg bg-slate-50 p-5">
          <p className="text-sm font-medium text-slate-600">
            Your Contributions
          </p>

          <p className="mt-2 text-2xl font-bold text-slate-900">
            {formatMoney(safeTotalContributions)}
          </p>

          <p className="mt-2 text-sm text-slate-600">
            This includes your initial investment and planned
            contributions over {years} years.
          </p>
        </div>

        {/* Interest Earned */}
        <div className="rounded-lg bg-purple-50 p-5">
          <p className="text-sm font-medium text-purple-700">
            Interest Earned
          </p>

          <p className="mt-2 text-2xl font-bold text-purple-900">
            {formatMoney(safeInterestEarned)}
          </p>

          <p className="mt-2 text-sm text-purple-700">
            This is the projected growth generated by compound
            interest.
          </p>
        </div>

        {/* Inflation Impact */}
        <div className="rounded-lg bg-orange-50 p-5">
          <p className="text-sm font-medium text-orange-700">
            Inflation Impact
          </p>

          <p className="mt-2 text-2xl font-bold text-orange-900">
            {formatMoney(safeInflationAdjustedValue)}
          </p>

          <p className="mt-2 text-sm text-orange-700">
            Estimated purchasing power after accounting for
            inflation.
          </p>

          <p className="mt-2 text-xs text-orange-600">
            Estimated purchasing-power reduction:{" "}
            {inflationImpactPercentage.toFixed(2)}%
          </p>
        </div>

        {/* Best Comparison */}
        {bestComparison && (
          <div className="rounded-lg bg-blue-50 p-5">
            <p className="text-sm font-medium text-blue-700">
              Highest Compared Rate
            </p>

            <p className="mt-2 text-2xl font-bold text-blue-900">
              {bestComparison.rate}%
            </p>

            <p className="mt-2 text-sm text-blue-700">
              Projected value:
            </p>

            <p className="mt-1 text-lg font-bold text-blue-900">
              {formatMoney(bestComparison.futureValue)}
            </p>
          </div>
        )}
      </div>

      {/* Summary */}
      <div className="mt-6 rounded-lg border border-slate-200 bg-slate-50 p-5">
        <h3 className="font-semibold text-slate-900">
          What this means
        </h3>

        <p className="mt-2 text-sm leading-6 text-slate-600">
          If you follow this investment plan for {years} years,
          your projected investment value is{" "}
          <span className="font-semibold text-slate-900">
            {formatMoney(safeFutureValue)}
          </span>
          . You would contribute approximately{" "}
          <span className="font-semibold text-slate-900">
            {formatMoney(safeTotalContributions)}
          </span>{" "}
          and potentially earn{" "}
          <span className="font-semibold text-slate-900">
            {formatMoney(safeInterestEarned)}
          </span>{" "}
          through investment growth.
        </p>
      </div>
    </section>
  );
}

export default FinancialInsights;